### ISSUE TITLE
Redux - Dark Matters (HB)

### ISSUE THREAD

**Issue by delon5** [Rinnegatamante/flycast-vita-compatibility-list#188] opened 2022-08-29 04:36 UTC
game img: cdi

The game runs at a pretty consistent 60fps with minimal slowdown when more enemies are on screen.

![7D8F9B03-4577-4E1C-8CA1-7E051C2EE2D2](https://user-images.githubusercontent.com/25923990/187123647-df5765cd-62e3-4dc3-93f0-c280bfdaaf4e.jpeg)

![C465100D-C4E9-4EC1-A5EF-6E569641069A](https://user-images.githubusercontent.com/25923990/187124478-2ff1979a-6a92-4985-866b-56b66ac4d41e.jpeg)

I would call this perfect.

GENERAL
pal
tv composite

VIDEO
Frame skipping - max
Per Strip
Shadows - yes
fog - yes
mipmaps - yes
use simple shaders - yes
delay frame swaping - yes

ADVANCED
idle skip
Float ops gamehack
use neon simd
self-modifying code checks - off
multi-threaded emulation

**Comment by Rinnegatamante** [comment] 2022-08-29 13:51
Duplicate of https://github.com/Rinnegatamante/flycast-vita-compatibility-list/issues/31

**Closed by Rinnegatamante** 2022-08-29 13:51 UTC
Labels: Perfect
